server:
  port: 8762

spring:
  profiles:
    active: default
---
spring:
  profiles: dev
server:
  port: 8763
---
spring:
  profiles: prod
server:
  port: 8084
---
spring:
  profiles: default
server:
  port: 8762
---

spring:
  application:
    name: test-common-service
  jackson:
    serialization: {FAIL_ON_EMPTY_BEANS: false}
  redis:
    database: 10
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      

    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/